version: '3'
services:  
  db:
    build:
      context: ./docker/db/
      dockerfile: Dockerfile
  web:
    build:
      context: ./
      dockerfile: ./docker/web/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db
    ports:
     - "8080:80"